doc-warnings: no
test-warnings: no
strictness: high
max-line-length: 100
autodetect: yes
ignore-paths:
    - doc
    - examples
    - pylint
python-targets:
    - 2
    - 3
pep8:
  disable:
    - W0212
    - E1101
    - F0401
    - E1103
    - W1201
    - W0142
    - W0622
    - W0221
    - W0231
    - W0614