language: python
python:
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  # command to install dependencies
install: "pip install -r requirements.txt --use-mirrors"
# command to install dependencies
script: python tests/all_tests.py
branches:
  only:
    - develop
